# -*- coding: utf-8 -*-
"""Exercicios_Condicionais.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11QkM3yyEZ1Vv-pgejMXkzrCosQmDdiY2

Bruno gerencia um pequeno comércio e quer saber qual produto teve o melhor desempenho de vendas no mês passado. Ele registrou a quantidade vendida de dois produtos: maçãs e bananas. Agora, ele precisa escrever um programa que identifique e exiba qual deles teve maior venda.

Crie um programa que receba o número de vendas dos dois produtos e exiba uma mensagem indicando qual deles vendeu mais. Se as quantidades forem iguais, exiba uma mensagem dizendo que houve empate.
"""

prod1 = int(input('Qual o numero de vendas do produto 1: '))
prod2 = int(input('Qual o numero de vendas do produto 2: '))

if prod1 == prod2:
  print('A venda dos dois produtos foi igual!')

elif prod1 > prod2:
  print('A venda do produto 1 foi maior')

else:
  print('A venda do produto 2 foi maior')

"""Camila está organizando um projeto e precisa calcular o tempo total necessário para concluir três atividades: A, B e C. No entanto, se alguma atividade tiver um número de dias negativo, o código deve avisar que os valores inseridos são inválidos e não calcular o total.

Escreva um programa que receba o número de dias de três atividades e exiba o tempo total do projeto. Se algum valor for negativo, mostre uma mensagem informando o erro.
"""

d1 = int(input('Digite quantos dias pro projeto 1: '))
d2 = int(input('Digite quantos dias pro projeto 2: '))
d3 = int(input('Digite quantos dias pro projeto 3: '))

if d1 < 0 or d2 < 0 or d3 < 0:
  print('Valor incoorreto!')
else:
  print(f'O total dos valores foi {d1 + d2 + d3}')

"""Lucas trabalha em TI e precisa garantir que a temperatura de uma sala de servidores não ultrapasse 25°C. Ele quer um programa que receba a temperatura atual como entrada e, se necessário, exiba uma mensagem de alerta."""

temp = int(input('Digite a temperatura atual: '))

if temp > 25:
  print('Alerta! Temperatura acima do permitido')
else:
  print('Temperatura abaixo do permitido')

"""Anna Júlia está criando um sistema para calcular o Índice de Massa Corporal (IMC) e fornecer recomendações básicas. O programa deve receber o peso e a altura de uma pessoa e exibir o valor do IMC, além de indicar se está abaixo do peso, com peso normal ou acima do peso. Crie um programa que receba o peso (em kg) e a altura (em metros) e calcule o IMC usando a fórmula: IMC = peso / (altura ** 2) Depois, exiba o valor do IMC e uma mensagem indicando se está abaixo do peso (IMC < 18.5), peso normal (18.5 <= IMC < 25) ou acima do peso (IMC >= 25)."""

altura = float(input('Digite sua altura (em metros): '))
peso = float(input('Digite seu peso (em Kg): '))

imc = peso / (altura ** 2)

print(f'Seu IMC é {imc:.2f}')
if imc >= 25:
  print('Voce está acima do peso')
elif imc >= 18.5:
  print('Seu peso está normal')
else:
  print('Voce está abaixo do peso')

"""Carlos quer monitorar seu orçamento mensal para evitar gastos excessivos. Ele estabeleceu um limite de R$ 3.000,00 para seus gastos e precisa de um programa que ajude a controlar suas despesas. O programa deve receber o total de despesas realizadas e informar se ele ultrapassou o limite ou ainda está dentro do orçamento."""

despesas = float(input('Digite suas despesas: '))

if despesas > 3000.00:
  print('Suas despesas estão acima do limite')
else:
  print('Suas despesas estão dentro do limite')

"""Mariana é responsável por liberar o acesso ao escritório e precisa de um programa que verifique se os funcionários podem entrar. Para isso, ela usará o horário atual. O escritório só permite acesso entre 8h e 18h. Crie um programa que receba a hora atual como entrada (em formato de 24 horas) e exiba uma mensagem informando se o acesso é permitido ou negado."""

hora = int(input('Digite a hora da entrada (no formato 24 horas): '))

if hora > 18 or hora < 8:
  print('Entrada negada, fora do horario permitido')
else:
  print('entrada liberada')

"""Uma professora precisa de um programa que ajude a calcular a média final dos alunos e informe se foram aprovados, ficaram de recuperação ou reprovados. As regras são:

Média >= 7: Aprovado

5 <= Média < 7: Recuperação

Média < 5: Reprovado

Escreva um programa que receba três notas como entrada e calcule a média final. Com base na média, exiba a situação do aluno.

"""

n1 = float(input('Digite a nota 1: '))
n2 = float(input('Digite a nota 2: '))
n3 = float(input('Digite a nota 3: '))

media = (n1 + n2 + n3) / 3

if media >= 7:
  print('Aluno aprovado')
elif media >= 5:
  print('Aluno de recuperação')
else:
  print('Aluno reprovado')

"""Fernanda está planejando uma viagem e quer calcular quanto pagará de pedágio. O valor do pedágio depende da distância percorrida:

Até 100 km: R$ 10,00

Entre 100 km e 200 km: R$ 20,00

Acima de 200 km: R$ 30,00

Crie um programa que receba a distância percorrida e informe o valor do pedágio correspondente.
"""

dist = float(input('Digite a distancia percorrida: '))

if dist > 200.00:
  print('O valor do pedágio será de 30.00 reais')
elif dist > 100.00:
  print('O valor do pedágio será de 20.00 reais')
if dist <= 100.00:
  print('O valor do pedágio será de 10.00 reais')

"""Lucas está desenvolvendo um jogo e precisa de uma funcionalidade que verifique se um número é par ou ímpar. Essa verificação será usada para definir ações diferentes dentro do jogo. Escreva um programa que receba um número inteiro e exiba uma mensagem informando se ele é par ou ímpar."""

num = int(input('Digite o numero: '))

if num % 2 == 0:
  print('Seu numero é par!')
else:
  print('Seu numero é impar!')

"""Pedro quer solicitar um empréstimo, mas a aprovação depende de duas condições:

O valor da renda mensal precisa ser maior que R$ 2.000,00.
O valor da parcela não pode ultrapassar 30% da renda.
Crie um programa que receba como entrada a renda mensal de Pedro e o valor da parcela desejada. O programa deve informar se o empréstimo foi aprovado ou negado com base nas condições acima.
"""

renda = float(input('Digite o valor da renda mensal: '))
parcela = float(input('Digite o valor da parcela: '))

trinta = renda * 0.30

if parcela <= trinta and renda > 2000.00:
  print('Empréstimo aprovado!')
else:
  print('Empréstimo reprovado!')